puppetlabs/trapperkeeper-webserver-jetty9

- project.clj
The Leiningen release plugin was complaining about these fields missing.
> (MAINT) Add license and URL fields to project.clj

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
This commit adds a `queue-max-size` setting for helping control the maximum number of incoming connections that can be queued by the webserver before any new connections are dropped.
> (TK-82) Added `queue-max-size` setting

- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
This updates the jvm-ca dependency to reflect the name change.
This also updates the Trapperkeeper dependency to the newest version.
> (SERVER-101) Upgrade jvm-ca dependency

- dev-resources/java.security
- project.clj
This commit bumps the dependencies in the project.clj file.  clj-time is
specifically pinned to 0.5.1 for compatibility with other current
Trapperkeeper library dependencies and to avoid the conflict that was
being pulled in from spyscope's dependency on clj-time.  The clojure
dependency was bumped to 1.6.0 since other Trapperkeeper projects are
incrementally having this bumped as well.
This commit also applies a technique first done in SERVER-332 to enable
the ability to run SSLv3-based unit tests on newer JDK versions that
disable the use of SSLv3 by default.
> (MAINT) Update deps and options for running SSLv3 unit tests

- doc/jetty-config.md
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
This commit allows the TCP SO_LINGER time used by the sockets underlying
webserver connectors to be configurable via a new webserver setting
called `so-linger-seconds`.  This is an optional setting that, if not
specified, will use the legacy behavior of SO_LINGER being disabled for
webserver sockets.
> (TK-140) Expose so-linger-seconds setting for webserver connectors

- doc/jetty-config.md
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
A problem that we have had a few times with Jetty is that, in order to try to
make it easy for our users to manage the application without having to be Jetty
experts, we run Jetty embedded and only surface a subset of its configuration
options that we believe the users might care about.
This provides a pretty nice UX in cases where we've plumbed the appropriate
settings through into our config before shipping a build, but, it can be
problematic when we are trying to debug a customer issue and we discover a
potentially-relevant Jetty setting that we haven't wired through to our
configuration files... it means that we can't toggle the Jetty config setting
without shipping them a new build.
After discovering how logback supports some basic Java scripting in their
EvaluatorFilters (via a …
> (TK-144) Add support for configuring Jetty via script

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- Also turns a higher-level use of schema/either into schema/conditional, for better error messages
- The docs around the defaults for these options (https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/blob/master/doc/jetty-config.md#cipher-suites) appear to be wrong, but I may be missing something subtle. Let me know if you want me to update them.
> (TK-133) Allow comma separated strings in ssl-protocols, cipher-suites

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_handlers_test.clj
This PR adds support for a new setting, `idle-timeout-milliseconds`, which can be used to control how long Jetty will allow a client connection to remain open with no activity.
> (TK-151) Add idle timeout setting

- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
This commit upgrades the tk-jetty9's Jetty dependency to 9.2.10.
> (TK-178) Upgrade Jetty dependency to 9.2.10

- doc/jetty-config.md
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_default_config_test.clj
This commit contains three primary changes:
1) Expose the ability to configure the number of `selector-threads` and
`acceptor-threads` that the webserver will spin up per "port" in a
server configuration.
2) Remove the library-imposed defaults for various thread-pool related
settings, including: acceptor-threads, selector-threads, max-threads,
and queue-max-size.  The service will now defer to Jetty to impose
its own default values for these settings.
3) In the process of removing library-imposed defaults, this commit
effectively removes the changes from TK-130.  The `max-threads` setting
will no longer automatically be bumped up above the minimum number of
threads that the server needs to boot if the number that the server
tries to use is insufficient and the user had not configured an …
> (TK-148) Expose selectors and acceptors and adjust thread defaults

- CHANGELOG.md
- project.clj
This commit updates the CHANGELOG.md for the tk-jetty9 1.3.0 release.
> (MAINT) Updated CHANGELOG.md for tk-jetty9 1.3.0 release

- project.clj
- src/puppetlabs/trapperkeeper/services/webrouting/webrouting_service_core.clj
The prismatic/plumbing and prismatic/schema library dependencies are
lagging behind the latest stable version. This will increasingly cause
conflicts in trapperkeeper projects. This patch updates the dependencies
and fixes several functions which were validating against schemas
incompatible with the new versions.
* Update project.clj dependencies
* Use protocol schema instead of the protocol object directly
> (TK-195) Update prismatic library dependencies

- README.md
This commit includes a couple of changes to the README.md:
1) Added a support section.
2) Corrected the Travis status link to point to the tk-jetty9 project
instead of tk-jetty7.
> (PE-11020) Added a support section to the README and fixed Travis link

- README.md
- src/puppetlabs/experimental/websockets/client.clj
- src/puppetlabs/trapperkeeper/services/webserver/experimental/jetty9_websockets.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_handlers_test.clj
Here we extend the WebSocketProtocol to add a three-arg variant of
close! which allows for the reason we are closing a connection to
be specified.
> (maint) add variant of websockets/close! with reason

- project.clj
This keeps it in line with the version used in puppet-server
> (MAINT) Upgrade to ssl-utils 0.8.1

- src/puppetlabs/trapperkeeper/services/webserver/experimental/jetty9_websockets.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_handlers_test.clj
Here we correct the implementation of the WebsocketProtocol for
WebSocketSend to not stomp the arity-1 version of close!.
> TK-270 Restore and test for 1-arity version of websockets/close!

- src/puppetlabs/trapperkeeper/services/webrouting/webrouting_service.clj
- src/puppetlabs/trapperkeeper/services/webrouting/webrouting_service_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webrouting/webrouting_service_test.clj
Here we add a get-server function that, similar to get-route, will return
the configured server for the current service with a specified id.
> Add get-server to WebroutingService protocol

- project.clj
This commit promotes org.clojure/java.jmx from a dev profile only to a
top-level dependency.  There is no real need for the production
tk-jetty9 jar to pull in the dependency at this point.  However, we
haven't found a way to have java.jmx be included as a direct dependency
of the 'testutils' jar such that users of the 'testutils' jar wouldn't
have to declare their own redundant dependency on org.clojure/java.jmx,
which is undesirable.
> (MAINT) Make java.jmx a top-level dependency

- CHANGELOG.md
There was an error deploying version 1.5.3 to clojars; this commit
updates the CHANGELOG to reflect that, and to prepare for a 1.5.4
release.
> (TK-338) Update CHANGELOG for 1.5.4 release

- dev-resources/logback.xml
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_default_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
This commit modifies our 'stop' logic so that we won't attempt
to destroy/unregister the mbeans more than once, in the event
that 'stop' gets called multiple times by TK.
Unfortunately, the main symptom that we see when we do try to
destroy/unregister the mbeans multiple times is a slew of really
nasty log messages from Jetty, which meant that the test for this
change needed to mess with test logging stuff, which had a ripple
effect that spilled over into some other files.
> (TK-133) Safer cleanup of mbeans during stop

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
Add a new option, `:cache-session-id`, that defaults to true
and allows the caching of the SSL session id.
> (TK-124) Add option for session id caching

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
Reverts puppetlabs/trapperkeeper-webserver-jetty9#141
@camlow325 Here's this if we need/want it.  I just realized we hadn't done it yet and @haus showed me the cool little button Github has to revert.
> Revert "(TK-124) Add option for session id caching"

- src/puppetlabs/trapperkeeper/services/webserver/jetty9_service.clj
In the stop method of the WebserverService, clear the MBeanContainer
class's static map of bean name fragments, which it uses to ensure that
bean names are unique when a name is not specified as the bean is
registered. Without this change, this static map leaks these name
fragments unless JMX metrics are specifically disabled in the TK config.
> (TK-372) Reset MBeanContainer's map of bean names.

- project.clj
This eliminates a conflict with the status and metrics services.
> (maint) bump java-jmx dependency to 0.3.1

- doc/jetty-config.md
- doc/webrouting-config.md
The setting in the map passed to the service is `jmx-enable` not `jmx-enabled` and I don't see anywhere were we do a translation from the past tense to the bare infinitive (+ the schema [WebserverRawConfig](https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/blob/master/src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj#L118), + the [translation of string -> bool](https://github.com/puppetlabs/trapperkeeper-webserver-jetty9/blob/master/src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj#L443) both refer to it as `jmx-enable`) so I'm relatively confident, without standing up a tk-jetty9 app, that the config file/user facing docs should also be `jmx-enable`.
Also fixes a broken inbound link to the doc in question.
> (maint) Fix typos in config docs

- .travis.yml
- project.clj
Logback is pulled in through trapperkeeper already and not needed or wanted
as an explicit dependency of tk-jetty9
> (MAINT) Remove explicit logback dependency

- locales/messages.pot
- src/puppetlabs/experimental/websockets/client.clj
- src/puppetlabs/trapperkeeper/services/webserver/experimental/jetty9_websockets.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_handlers_test.clj
Adds uri-path to the WebsocketProtocol and implementation. This caches
the URI used in the upgrade request to establish a websocket connection
so we can retrieve it even after the session has closed. It also caches
the remote address for the same purpose.
> Add uri-path to websocket adapter

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
This commit exposes a new webserver setting, request-body-max-size,
which can be used to configure the maximum HTTP Content-Length that
the Jetty webserver will accept for an incoming request.  If the
limit is exceeded, the request fails with a 413 error.  If the
setting is not present in configuration or the Content-Length
header is not present in the request, the request will be passed through
to underlying handlers for evaluation.
> (SERVER-1695) Expose a request-body-max-size webserver setting

- CHANGELOG.md
- project.clj
Update CHANGELOG.md and project.clj file for the 1.7.0 release.
> (MAINT) Prep for 1.7.0 release

- .travis.yml
- CHANGELOG.md
- README.md
- doc/jetty-config.md
- java/com/puppetlabs/trapperkeeper/services/webserver/jetty9/utils/LifeCycleImplementingRequestLogImpl.java
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- src/puppetlabs/trapperkeeper/services/webserver/normalized_uri_helpers.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_default_config_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_proxy_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/normalized_uri_helpers_test.clj
- test/java/appender/TestListAppender.java
This commit updates jetty to 9.4.1, which requires several changes to
tests and the config and core namespaces. Here are a list of changes and
why they were made:
Code changes
* Manually start the request logger when set
This change
eclipse/jetty.project@34a8da2
seems to have caused logging to no longer work without starting here.
Starting after the server was started did not do the right thing.
* GzipHandler changes
GzipHandler moved into a new package, into jetty-server from
jetty-servlets and some of the setup methods changed, notably
around excluding mime types.
* ProxyServlet changes
Several methods in the ProxyServlet and AbstractProxyServlet were
deprecated, so the methods being proxied also have been updated.
* Enable client redirects
The http connection used for proxies began …
> (TK-369) Update jetty dependency to 9.4.1

- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
Previously, if the 'no graceful shutdown' test failed due to the server
not closing the socket when the server was stopped, this test could
hang.  This commit reworks the test steps to hopefully avoid hanging the
test suite in the event of this kind of failure.  There does still
appear to be an underlying bug in Jetty here but it has proven very
difficult to reliably reproduce.
> (TK-437) Reworked no graceful shutdown test to avoid hang

- examples/ring_app/bootstrap.cfg
- java/com/puppetlabs/trapperkeeper/services/webserver/jetty9/utils/InternalSslContextFactory.java
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_service.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
This commit uses the tk-filesystem-watcher service to register a change
notification for the CRL file given to the Jetty webserver.  On
detection of a change, the Jetty SSLContextFactory is reloaded.  This
allows for the updated CRL file to be used without requiring a full
webserver restart.  Runtime CRL updating now occurs when tk-jetty9 is
used in a webservice stack which includes the optional
tk-filesystem-watcher dependency.
> (TK-149) Reload the crl file in the running webservers on change

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
Previously we included an invalid cipher suite in our list of cipher
suites to register.
This causes a warning to be logged at start up.
This patch removes the invalid cipher suite from the list of cipher
suites we register.
> (TK-449) Remove invalid cipher suite

- .travis.yml
- CHANGELOG.md
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_service.clj
This commit updates the add-watch-dir! call that we use to watch the crl
directory for changes to use the non-recursive option. We do so to address an
issue we were seeing where during the normal lifecycle of puppetserver run, it
was possible to create a directory that the watch service could not traverse,
causing the service to fail. With recursive false, we do not expect the service
to fail.
Signed-off-by: Moses Mendoza <moses@puppet.com>
> (TK-448) use non-recursive form of watch service watcher

- ext/travisci/test.sh
Travis has stopped including `lein2`, but we don't need to use it
specifically, so this PR updates the Travis script to just use `lein`.
> (maint) Switch to using `lein` instead of `lein2` in Travis

- doc/jetty-config.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
Introduced a new parameter to disallow renegotiation with default set to true. Done to address security vulnerability that allows a client to DoS any Jetty based puppet service.
This will affect all services using TK-webserver-jetty9. Some limited testing has been done using puppet server. Pl refer to comments in SERVER-1597 and related  tickets if enabling this could adversely impact your service. 
Would like to know if there any acceptance tests that need to be run separately besides this PR.
> (SERVER-1597) Add support for renegotiationAllowed configuration

- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
This commit adds POST requests to the list of HTTP methods that can be
gzipped by jetty. By default, only GET requests can request gzipping,
but we fetch catalogs via a post request, and need that response to be
gzipped as well.
> (SERVER-2118) Ensure that post request responses can be gzipped

- project.clj
This commit bumps the clj-parent version to 1.7.5, which is the version used
by PE 2018.1 components. The lein-parent version is also bumped to 0.3.4.
> (maint) Bump clj-parent version

- dev-resources/puppetlabs/trapperkeeper/services/webserver/request-logging.xml
- doc/jetty-config.md
- doc/request-logging-example-config.xml
- java/com/puppetlabs/trapperkeeper/services/webserver/jetty9/utils/MDCAccessLogConverter.java
- java/com/puppetlabs/trapperkeeper/services/webserver/jetty9/utils/MDCRequestLogHandler.java
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_core_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
- test/clj/puppetlabs/trapperkeeper/testutils/webserver/common.clj
This PR enhances the Jetty handlers to provide access to the SLF4J [Mapped Diagnostic Context](https://logback.qos.ch/manual/mdc.html) (MDC). The MDC is a thread-local storage for diagnostic information that can be directly accessed by Logback loggers.
The commits in this PR provide the following features when access logging is enabled:
- A snapshot of the data in the MDC is taken at the end of each request and folded into the request instance. The MDC is also restored to the state it had at the beginning of the request so that diagnostic data does not leak between requests that are handled by the same worker thread.
- The logback-access library is configured with support for the `%X` and `%mdc` pattern conversion words used by `logback-classic`. These can be used to add data stored in …
> (TK-470) Add support for the Mapped Diagnostic Context

- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
Previously, responses from jetty included a `Server` header with the
jetty version. Because we package applications as uberjars, making the
jetty manifest inaccessible, the server version was imprecise (ie.
9.4.z-SNAPSHOT vs. 9.4.11.v20180605). That fact makes the version header
not particularly useful and can also confuse security scanners, which
can't determine whether the server is patched for a particular
vulnerability.
This commit disables sending the `Server` header in responses. It also
prevents default HTML responses from including the server version. No
option is provided to reenable the header, since it's not really useful
and there's presently no reason to include it.
> (TK-473) Stop reporting jetty version in responses

- CHANGELOG.md
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/experimental/jetty9_websockets.clj
When disconnect is called on a connection that is already closed it throws an error. We only want to disconnect if the connection has not already been closed, so this adds an if block to check that `getSession` is not null before disconnecting the session.
> (PCP-862) Only disconnect if the connection is not closed

- .travis.yml
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
Jetty warns if a contextPath is an empty string. Since that is normal in
clients of this library, substitute "/" in this case, which is what
jetty ends up using anyway.
> (maint) Suppress warning about empty contextPath

- CHANGELOG.md
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
Prior to 3.0 we allowed and claimed to honor setting the socket linger
setting. In 3.0 we removed this setting since it was removed in Jetty
after the maintainers found out that it had undefined behavior on their
target platforms.
Unfortunately, none of the projects that pull in tk-jetty9 wrap the
configuration parsing sufficiently to intercept this configuration and
provide a kinder upgrade path. Nor are those projects in a position to
break their config APIs in a release soon.
Consequently, we now allow the old config value in our schema, though
ignore it in further processing to provide a smoother upgrade path to
users.
> (SERVER-2576) Loosen schema to allow so-linger-seconds key

- dev-resources/logback.xml
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_config.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
Fixing some wiring to the SslContextFactory in FIPS mode that was
causing jetty to be extra noisy. Specifically, this will stop these log
messages from occurring:
2019-10-16 12:04:50,761 INFO  [o.e.j.u.s.SslContextFactory] No Cipher matching 'TLS_DHE_RSA_WITH_AES_128_GCM_SHA256' is supported
2019-10-16 12:04:50,761 INFO  [o.e.j.u.s.SslContextFactory] No Cipher matching 'TLS_DHE_RSA_WITH_AES_256_GCM_SHA384' is supported
2019-10-16 12:04:50,761 INFO  [o.e.j.u.s.SslContextFactory] No Cipher matching 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384' is supported
2019-10-16 12:04:52,769 INFO  [o.e.j.u.s.SslContextFactory] Unable to get CertificateFactory instance for type [X.509] on provider [BCJSSE], using default
Note: this involved removing three supported ciphers from the default
list, so that will …
> (maint) fixing misconfiguration causing noise

- .travis.yml
- project.clj
Updates clj-parent for new clj-http-client and enables FIPS tests
> (PE-26658) update clj-parent to pick up fips work

- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
This commit adds a type annotation to indicate which version of Jetty's
`newResource` function is desired.
> (SERVER-2734) Disambiguate overloaded method call

- java/com/puppetlabs/trapperkeeper/services/webserver/jetty9/utils/InternalSslContextFactory.java
- project.clj
- src/puppetlabs/trapperkeeper/services/webserver/jetty9_core.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_proxy_test.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/normalized_uri_helpers_test.clj
This updates us to the newest Jetty verion.
This required two changes. One was test changes around CVE-2016-2785 and
the other involves our custom SslContextFactory.
For background on CVE-2016-2785, see
[TK-343](https://tickets.puppetlabs.com/browse/TK-343) about how certain
percent encodings could be used to create a directory traversal attack.
In [#4033](https://github.com/eclipse/jetty.project/issues/4033), the
Jetty maintainers, in response to a user who got an NPE when attempting
to serve files from his jar by percent encoding a jar path, loosened the
percent encoding rules. Quickly after merging those loosened validation
rules, it was reverted and the rules were additionally tightened up. As
part of that tightening, some of the dangerous percent encodings Jetty
used to let through …
> (SERVER-2800) Update Jetty to 9.4.28

- project.clj
This update contains a few security fixes.
> (PE-30976) Update Jetty to 9.4.36.v20210114

- CHANGELOG.md
- project.clj
This commit updates flatland to latest, to match what's pulled in by
other libraries, notably clj-yaml.
> (maint) Update flatland to 1.5.9

- project.clj
- CVE-2021-28165 - #6072 - jetty server high CPU when client send data length > 17408
- CVE-2021-28164 - #6101 - Normalize ambiguous URIs
- CVE-2021-28163 - #6102 - Exclude webapps directory from deployment scan
> (SEC-431) update jetty to 9.4.39.v20210325 to resolve CVEs

- CHANGELOG.md
- project.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_config_test.clj
We do not currently use the features affected by CVE-2021-28169, however
we should take this opportunity to update to the latest z release of
Jetty.
Here is the Jetty changelog:
```
jetty-9.4.42.v20210604 - 04 June 2021
+ 5379 Better handling for wrong SNI
+ 5931 SslConnection should implement getBytesIn()/getBytesOut()
+ 6118 Display a warning when Hazelcast configuration does not contain Jetty
session serializer
+ 6276 Support non-standard domains in SNI and X509
+ 6287 Class loading broken for WebSocketClient used inside webapp
+ 6323 HttpClient gets stuck/never calls onComplete() when multiple requests
with timeouts are sent
jetty-9.4.41.v20210516 - 16 May 2021
+ 6099 Cipher preference may break SNI if certificates have different key
types
+ 6186 Add Null Protection on Log / Logger
+ …
```
> (SERVER-3035) Update Jetty to 9.4.42

- CHANGELOG.md
We had already updated to 9.4.42 in the previous release, this was probably just
a copy+paste error.
> (maint) Fix CHANGELOG

- CHANGELOG.md
- project.clj
This updates jetty to 9.4.48.  From the jetty changelog:
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.48.v20220622
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.47.v20220610
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.46.v20220331
https://github.com/eclipse/jetty.project/releases/tag/jetty-9.4.45.v20220203
> (maint) bump jetty to 9.4.48.v20220622

- .travis.yml
- CHANGELOG.md
- project.clj
- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
This updates clj-parent to 5.2.6 to include the new version of bouncy-castle which has been renamed from `15on` to `18on` to indicate that it is now only jdk8 and beyond compatible.
Additionally the changelog was updated to prepare for a new 4.4.0 release.
> (maint) update clj-parent to 5.2.6

- CHANGELOG.md
- project.clj
This updates the clj-parent version to 5.2.9, which contains a version declaration for stylefruits/gniazdo, allowing the version in this repository to not pin a specific version.
> (PE-34658) Bump clj-parent to remove stylefruits/gniazdo version

- .travis.yml
- project.clj
The stylefruits library is only used in tests, and as a result doesn't need to be a full dependency.  This moves it to the dev section so that it is available for tests, but not part of the overall jar.
> (maint) move stylefruits/gniazdo to dev section

- CHANGELOG.md
- project.clj
This updates jetty 9 to 9.4.51.v20230217 to address CVE-2023-26048 and CVE-2023-26049
> (PE-35872) update jetty to 9.4.51.v20230217 to address CVE

- CHANGELOG.md
The version numbers were incorrect in the changeling.  This updates them to the correct versions.
> (maint) update changeling

- CHANGELOG.md
- project.clj
This addresses multiple CVEs found in the previous jetty version:
* https://github.com/advisories/GHSA-58qw-p7qm-5rvh
* https://github.com/advisories/GHSA-hmr7-m48g-48f6
* https://github.com/advisories/GHSA-3gh6-v5v9-6v9j
* https://github.com/advisories/GHSA-pwh8-58vv-vw48
> (PE-36842) update jetty to 9.4.52.v20230823

- test/clj/puppetlabs/trapperkeeper/services/webserver/jetty9_service_test.clj
The service test contained a regular expression that matched on the size of the content. The headers that are included in the response depend on the platform and java version that are used to run the tests, so this removes the size part of the regular expression to make the tests less sensitive to environment. The underlying behavior in the test isn't impacted; it still validates that the logging occurred.
> (maint) make service test less sensitive

- .github/workflows/lein-test.yaml
- .github/workflows/mend.yaml
- project.clj
This updates clj-parent to the latest version in the 5.x branch, updates the github actions to have the latest dependency versions, which was preventing scans from operating correctly, adds a scheduled scan.
Finally it removes the deprecated mixed vector/maps dependencies declarations in project.clj
> (maint) udpate clj-parent, github-actions, and project.clj
